# Generated by Django 4.1.13 on 2024-05-31 20:34

from django.db import migrations, models
import djongo.models.fields
import medical_records_service.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('patient_id', models.CharField(max_length=24)),
                ('doctor_id', models.CharField(max_length=24)),
                ('visit_date', models.DateField()),
                ('diagnosis', models.TextField()),
                ('prescriptions', djongo.models.fields.ArrayField(model_container=medical_records_service.models.Prescription)),
                ('doctor_notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('medication_id', models.CharField(max_length=24)),
                ('name', models.CharField(max_length=255)),
                ('dosage', models.CharField(max_length=255)),
                ('frequency', models.CharField(max_length=255)),
            ],
        ),
    ]
